// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvoXPd4LzA4O6Ee9CbakzvWTQ6rirCpmo',
    appId: '1:1049374597868:web:e6071f25a10991056f7bc9',
    messagingSenderId: '1049374597868',
    projectId: 'my-site-710d2',
    authDomain: 'my-site-710d2.firebaseapp.com',
    databaseURL: 'https://my-site-710d2-default-rtdb.firebaseio.com',
    storageBucket: 'my-site-710d2.appspot.com',
    measurementId: 'G-QMVDQ44478',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj8xcR6t7Az7HgLarznFh18zdcaX0yvis',
    appId: '1:1049374597868:android:3ba734e93fc4300e6f7bc9',
    messagingSenderId: '1049374597868',
    projectId: 'my-site-710d2',
    databaseURL: 'https://my-site-710d2-default-rtdb.firebaseio.com',
    storageBucket: 'my-site-710d2.appspot.com',
  );
}
